<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2018  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<div style="overflow-x: auto;">
<table class="mt-5 text-nowrap table-sm table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col" colspan="2"><?php echo($this->tableTitle); ?></th>
            <th scope="col" style="text-align: right">
                <?php if($this->permission->createAllowed()): ?>
                <form id="<?php echo($this->getPathSimplified()); ?>" class="noshow">
                    <div class="row">
                        <label for="title" class="col-sm-3 col-form-label">Beschreibung</label>
                        <div class="col-sm-8">
                            <input
                                type="text"
                                class="form-control form-control-sm"
                                placeholder="Hier kommt die Beschreibung hin..."
                                maxlength="100"
                                title="Gib hier bitte eine kurze Beschreibung der Datei ein."
                                id="title"
                                name="title"
                                value=""
                                required
                            />
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                    <div class="row">
                        <label for="division" class="col-sm-3 col-form-label">Datei</label>
                        <div class="col-sm-8 fileupload">

                            <!-- FIXME --- 8x ---- 8x --- !-->
                <div class="custom-file">
                    <input data-onlyimage="false" type="file" class="custom-file-input" id="customFile">
                    <div class="invalid-feedback"></div>
                    <label class="custom-file-label" for="customFile">Datei auswählen</label>
                </div>

                <script>
                $(document).ready(function () {
                    bsCustomFileInput.init();
                });
                </script>
                <div class="noshow progress mt-2">
                    <div id="progressbar-file" class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
                </div>

                            <?php /*

                            <div class="dropzone">
                                <a class="btnRemove noshow" href="#">x</a>
                                <div class="noshow clearFileSelect">
                                    <input
                                        class="fileselectupload"
                                        type="file"
                                        name="file"
                                        style="width: 24em;"
                                    />
                                </div>
                                <div class="fileSelectDescr">
                                    Datei hier ablegen oder klicken zum Hochladen
                                </div>
                                <div class="currfile" ></div>
                            </div>
*/ ?>
                            <!-- 8x ---- 8x --- !-->

                        </div>
                    </div>
                </form>
                <button
                    type="button"
                    class="btn btn-success btn-sm"
                    data-toggle="modal"
                    data-target="#createDialogModal"
                    data-url="<?php echo($this->getCurrentPath()); ?>"
                    data-form-id="<?php echo($this->getPathSimplified()); ?>"
                >Neuer Eintrag</button>
                <?php endif;?>
            </th>
        </tr>
    </thead>
    <tbody class="text-nowrap reload-data" data-url="<?php echo($this->getCurrentPath()); ?>">
    </tbody>
</table>
</div>